# Generated by Django 3.0.2 on 2020-01-15 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='send_to',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
