# Generated by Django 3.0.2 on 2020-01-15 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_coupon_send_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount_test',
            field=models.CharField(default=models.IntegerField(), max_length=100),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='modified_at',
            field=models.DateTimeField(verbose_name='modified_Date'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='send_to',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
